// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmdAexGHSZXcEAR_sGchrXJ8uaOdaUKlY',
    appId: '1:1014294043694:web:eb58524ca1ee63f77a93bf',
    messagingSenderId: '1014294043694',
    projectId: 'r13note-supermarket-ads',
    authDomain: 'r13note-supermarket-ads.firebaseapp.com',
    storageBucket: 'r13note-supermarket-ads.firebasestorage.app',
    measurementId: 'G-V16HJ5KNHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxarpKvSYUvOYh0trnN7OSgj3dD4TO--I',
    appId: '1:1014294043694:android:5f4613dd7ea6c9527a93bf',
    messagingSenderId: '1014294043694',
    projectId: 'r13note-supermarket-ads',
    storageBucket: 'r13note-supermarket-ads.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrfMd94NBDJM52E1HDj5Y0ZTHbmmfDq5I',
    appId: '1:1014294043694:ios:8d4e739c37ab4d627a93bf',
    messagingSenderId: '1014294043694',
    projectId: 'r13note-supermarket-ads',
    storageBucket: 'r13note-supermarket-ads.firebasestorage.app',
    iosBundleId: 'com.r13.supermarketAds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrfMd94NBDJM52E1HDj5Y0ZTHbmmfDq5I',
    appId: '1:1014294043694:ios:7483370f59ce4cfb7a93bf',
    messagingSenderId: '1014294043694',
    projectId: 'r13note-supermarket-ads',
    storageBucket: 'r13note-supermarket-ads.firebasestorage.app',
    iosBundleId: 'com.example.supermarketAds',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmdAexGHSZXcEAR_sGchrXJ8uaOdaUKlY',
    appId: '1:1014294043694:web:6518e51a03b16e037a93bf',
    messagingSenderId: '1014294043694',
    projectId: 'r13note-supermarket-ads',
    authDomain: 'r13note-supermarket-ads.firebaseapp.com',
    storageBucket: 'r13note-supermarket-ads.firebasestorage.app',
    measurementId: 'G-ZY8PRRD1XL',
  );

}